Repository pi-hole/web, pull requests merged in 2018-12, with the labels that each got.

#864 Some improvements to Settings page
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: Enhancement

#866 Prevent possible attacks via admin email setting
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix, Security

#871 Don't use --quiet flag for adding hosts to white- and blacklist
  list.php
  scripts/pi-hole/js/list.js
  scripts/pi-hole/php/add.php
Labels: Bugfix

#862 Release v4.1
  README.md
  api.php
  api_FTL.php
  api_db.php
  db_queries.php
  help.php
  index.php
  list.php
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/list.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/get.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/queryads.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sub.php
  scripts/pi-hole/php/teleporter.php
  settings.php
Labels: Release

#876 Release v4.1.1
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sub.php
Labels: Release

#879 Merge hotfix v4.1.1 into dev
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sub.php
Labels: Release
