Repository pi-hole/web, pull requests merged in 2018-04, with the labels that each got.

#711 Add separate legends for pie charts on the dashboard
  index.php
  scripts/pi-hole/js/index.js
  style/pi-hole.css
Labels: Bugfix

#713 Add settings for privacy level
  scripts/pi-hole/js/index.js
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: Enhancement

#701 align this readme with the core one. formatting and layout is now th…
  README.md
Labels: Ready for Check and Merge

#696 Use better client host name caching for DB queries
  api_db.php
Labels: Bugfix

#721 Add cache-control meta tag
  scripts/pi-hole/php/header.php
Labels: Bugfix, Enhancement

#724 Use host names from FTLDNS
  api_FTL.php
Labels: Enhancement

#700 Add custom tooltip for Clients over Time graph
  index.php
  scripts/pi-hole/js/index.js
  style/pi-hole.css
Labels: Bugfix

#728 Add frontend changes for supporting a local DNS server
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: Enhancement

#730 Make sure backend does always interpret list of DNS servers even if it is empty
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#734 Display number of lists used in title of settings > blocklist
  settings.php
Labels: Enhancement

#739 Update warnings on settings page buttons
  scripts/pi-hole/js/settings.js
Labels: Enhancement
