Repository pi-hole/web, pull requests merged in 2018-08, with the labels that each got.

#810 Add deprecation notification for FTLDNS branches
  scripts/pi-hole/js/index.js
  scripts/pi-hole/php/header.php
Labels: Enhancement

#811 Acknowledge possible custom time interval
  index.php
  scripts/pi-hole/php/header.php
  settings.php
Labels: Enhancement

#812 Don't require adlists to start in "http"
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#815 Pie-chart custom tooltips
  index.php
  scripts/pi-hole/js/index.js
Labels: Bugfix

#816 Offer possibility to import auditlog.list from teleporter archive
  scripts/pi-hole/php/teleporter.php
  settings.php
Labels: Enhancement

#824 Change "Pi-holed" to "Blocked" on the Query Log
  scripts/pi-hole/js/queries.js
Labels: Enhancement

#828 Add support for new query statuses in long term query log
  scripts/pi-hole/js/db_queries.js
Labels: Bugfix

#826 Use random colors in client graph if presets run out
  scripts/pi-hole/js/index.js
Labels: Bugfix

#832 Improve "Wrong Token." message
  scripts/pi-hole/php/auth.php
Labels: Enhancement

#833 Fix whitelisting from the query log (and DB query log)
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
Labels: Bugfix

#838 Improve DNS server settings tab
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: Enhancement

#830 Add DNS cache information to Settings page
  api_FTL.php
  scripts/pi-hole/js/settings.js
  settings.php
Labels: Enhancement

#831 Add query type selection for Long-term Query Log
  api_db.php
  db_queries.php
  scripts/pi-hole/js/db_queries.js
Labels: Enhancement

#839 Add Quad9 secondary IPv6 IP addresses
  scripts/pi-hole/php/savesettings.php
Labels: Discourse Feature Request
