Repository pi-hole/web, pull requests merged in 2018-07, with the labels that each got.

#783 Warn if privacy level > 0 but query logging activated
  settings.php
Labels: Enhancement

#772 Use regex lists instead of wildcards for blocking
  help.php
  list.php
  scripts/pi-hole/js/list.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/get.php
  scripts/pi-hole/php/sub.php
Labels: Enhancement, Requires Testing

#787 Fix clients over time tooltip height and "lag" issues
  scripts/pi-hole/js/index.js
Labels: Bugfix

#794 Fill in empty db graph data intervals with zero
  api_db.php
Labels: Bugfix

#797 Link to docs is 404. Add target landing page.
  list.php
Labels: Bugfix
