Repository pi-hole/web, pull requests merged in 2018-06, with the labels that each got.

#764 Query Log: Remember last selected "Show X entries"
  scripts/pi-hole/js/queries.js
Labels: Discourse Feature Request, Enhancement

#767 add patreon and adjust affiliate links
  README.md
Labels: Ready for Check and Merge

#762 Settings page: Display PHP errors
  scripts/pi-hole/js/settings.js
  settings.php
Labels: Bugfix, Enhancement

#769 Add "versions" endpoint ot API
  api.php
Labels: Discourse Feature Request

#763 Query Log: Remove DNSSEC column
  queries.php
  scripts/pi-hole/js/queries.js
Labels: Enhancement

#777 Improve readability of long term summary stats
  scripts/pi-hole/js/db_queries.js
Labels: Bugfix
