Repository pi-hole/web, pull requests merged in 2019-09, with the labels that each got.

#986 Add whitelist regex support
  list.php
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/list.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/get.php
  scripts/pi-hole/php/sub.php
  scripts/pi-hole/php/teleporter.php
  settings.php
Labels: Discourse Feature Request, Enhancement, WIP

#1000 Pass possible exception from SQLite3_connect_try() to the calling pro…
  scripts/pi-hole/php/database.php
Labels: Bugfix, Enhancement

#1004 Fix Teleporter adlist export issue (development only bug)
  scripts/pi-hole/php/teleporter.php
Labels: Bugfix

#1005 Fix some XSS issues in settings.php
  settings.php
Labels: Bugfix

#1003 Pi-hole Web v4.3.2
  .github/PULL_REQUEST_TEMPLATE.md
  api_db.php
  auditlog.php
  db_graph.php
  db_lists.php
  db_queries.php
  index.php
  list.php
  network.php
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/ip-address-sorting.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/loginpage.php
  scripts/pi-hole/php/savesettings.php
  scripts/vendor/daterangepicker.js
  settings.php
  style/pi-hole.css
  style/vendor/daterangepicker.css
Labels: Release
