Repository pi-hole/web, pull requests merged in 2019-05, with the labels that each got.

#933 Store domains in a database
  api_db.php
  scripts/pi-hole/js/list.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/get.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sub.php
  settings.php
  style/pi-hole.css
Labels: Requires Testing

#926 Pi-hole Web v4.3
  api_db.php
  db_graph.php
  db_lists.php
  db_queries.php
  network.php
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/get.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/queryads.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sub.php
  scripts/vendor/jquery.inputmask.extensions.js
  scripts/vendor/jquery.inputmask.js
  settings.php
  style/pi-hole.css
  style/vendor/font-awesome-4.5.0/css/font-awesome.min.css
  style/vendor/font-awesome-4.5.0/fonts/FontAwesome.otf
  style/vendor/font-awesome-4.5.0/fonts/fontawesome-webfont.eot
  style/vendor/font-awesome-4.5.0/fonts/fontawesome-webfont.svg
  style/vendor/font-awesome-4.5.0/fonts/fontawesome-webfont.ttf
  style/vendor/font-awesome-4.5.0/fonts/fontawesome-webfont.woff
  style/vendor/font-awesome-4.5.0/fonts/fontawesome-webfont.woff2
  style/vendor/font-awesome-5.6.3/css/all.min.css
  style/vendor/font-awesome-5.6.3/webfonts/fa-brands-400.eot
  style/vendor/font-awesome-5.6.3/webfonts/fa-brands-400.svg
  style/vendor/font-awesome-5.6.3/webfonts/fa-brands-400.ttf
  style/vendor/font-awesome-5.6.3/webfonts/fa-brands-400.woff
  style/vendor/font-awesome-5.6.3/webfonts/fa-brands-400.woff2
  style/vendor/font-awesome-5.6.3/webfonts/fa-regular-400.eot
  style/vendor/font-awesome-5.6.3/webfonts/fa-regular-400.svg
  style/vendor/font-awesome-5.6.3/webfonts/fa-regular-400.ttf
  style/vendor/font-awesome-5.6.3/webfonts/fa-regular-400.woff
  style/vendor/font-awesome-5.6.3/webfonts/fa-regular-400.woff2
  style/vendor/font-awesome-5.6.3/webfonts/fa-solid-900.eot
  style/vendor/font-awesome-5.6.3/webfonts/fa-solid-900.svg
  style/vendor/font-awesome-5.6.3/webfonts/fa-solid-900.ttf
  style/vendor/font-awesome-5.6.3/webfonts/fa-solid-900.woff
  style/vendor/font-awesome-5.6.3/webfonts/fa-solid-900.woff2
Labels: Release

#942 Replace fa-refresh with fa-sync
  auditlog.php
  db_graph.php
  db_lists.php
  index.php
  list.php
Labels: Bugfix

#946 Fix the sidebar toggle from overflowing when hovered over
  style/pi-hole.css
Labels: Bugfix

#948 Add correct IP sorting for the ARP table
  network.php
  scripts/pi-hole/js/ip-address-sorting.js
  scripts/pi-hole/js/network.js
Labels: Bugfix

#935 Fix audit log button being too wide
  auditlog.php
Labels: Bugfix
