Repository pi-hole/web, pull requests merged in 2019-07, with the labels that each got.

#974 Prevent command injection via admin email
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#964 Add IPv6 support for network table
  api_db.php
  scripts/pi-hole/js/network.js
Labels: Discourse Feature Request, Enhancement

#976 Upgrade the exporter/importer (teleporter) to use the gravity database
  scripts/pi-hole/php/teleporter.php
Labels: Bugfix

#975 Use the renamed adlist table when getting adlists
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#972 Don't show the "Click to ..." tooltip when filtering is disabled
  scripts/pi-hole/js/queries.js
Labels: Bugfix

#978 Audit log: Should use $domains
  scripts/pi-hole/php/add.php
Labels: Bugfix

#977 Feature: Batch audit requests
  scripts/pi-hole/js/auditlog.js
Labels: Enhancement

#968 Lists: Highlight if domains are disabled
  scripts/pi-hole/js/list.js
  scripts/pi-hole/php/get.php
Labels: Enhancement

#980 Prevent static DHCP leases from having duplicate hostnames
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix
