Repository pi-hole/web, pull requests merged in 2019-02, with the labels that each got.

#899 Fill long-term data daterange field with initialization value
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/db_queries.js
Labels: Bugfix

#903 Release v4.2
  auditlog.php
  db_graph.php
  db_lists.php
  db_queries.php
  debug.php
  gravity.php
  index.php
  list.php
  queries.php
  queryads.php
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/php/footer.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/savesettings.php
  settings.php
  taillog-FTL.php
  taillog.php
Labels: Release

#915 Remove dead code from scripts/pi-hole/js/index.js
  scripts/pi-hole/js/index.js
Labels: Code maintenance

#909 Implement finer grained external blocking displaying
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
Labels: Enhancement

#918 Long-term queries: Request all externally blocked variants when the checkbox is enabled
  scripts/pi-hole/js/db_queries.js
Labels: Bugfix
