Repository pi-hole/web, pull requests merged in 2020-11, with the labels that each got.

#1284 Use two different divs for mobile and desktop instead of a JS solution
  queryads.php
  scripts/pi-hole/js/queryads.js
Labels: Merge Conflicts

#1393 Fix initial visibility of group selector on simplified black- and whitelist pages
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
Labels: Bugfix

#1610 Add new query status 12 and 13 (retried queries)
  db_queries.php
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
Labels: PR: Approval Required

#1622 Add altKey to modifiers when clicking on query log
  queries.php
  scripts/pi-hole/js/queries.js
Labels: PR: Approval Required

#1627 Show detailed upstream destination in Query Log(s)
  api_db.php
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
Labels: PR: Approved, PR: Code Review Required

#1630 Print fatal dnsmasq errors
  scripts/pi-hole/js/messages.js
Labels: Enhancement

#1626 Ensure empty clients/groups/adlists/audits cannot be added
  scripts/pi-hole/php/groups.php
Labels: Bugfix

#1625 Add new replace_domain action to allow adding domain(s) exclusively to a specific list
  db_queries.php
  queries.php
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/utils.js
  scripts/pi-hole/php/groups.php
Labels: Bugfix

#1634 Add button to remove dynamic DHCP leases
  api_FTL.php
  scripts/pi-hole/js/settings.js
  settings.php
Labels: Discourse Feature Request, PR: Approval Required
