Repository pi-hole/web, pull requests merged in 2020-03, with the labels that each got.

#1177 tabs for new domain/regex input
  groups-domains.php
  scripts/pi-hole/js/groups-domains.js
Labels: Enhancement

#1184 Improve domain pages
  groups-domains.php
  scripts/pi-hole/js/groups-domains.js
Labels: Enhancement

#1181 Add IPv4/IPv6 address validation to clients management page
  groups-clients.php
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-common.js
Labels: Enhancement

#1200 Check adlist URL for valid characters before adding record to the database
  scripts/pi-hole/php/groups.php
Labels: Enhancement, Security

#1189 Add support for NAPTR query type
  api_db.php
Labels: Enhancement

#1187 Hide mock hardware addresses
  scripts/pi-hole/js/network.js
Labels: Enhancement

#1199 Remember last state of the "Apply filtering" checkbox on the Query Log page
  queries.php
  scripts/pi-hole/js/queries.js
Labels: Discourse Feature Request, Enhancement

#1149 Allow space separated multiple items injection
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: Enhancement

#1161 Add class "breakall" also to the code fields in the other tables.
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
Labels: Enhancement
