Repository pi-hole/web, pull requests merged in 2020-05, with the labels that each got.

#1234 Fill missing time intervals with zero
  api_db.php
Labels: Bugfix

#1224 Improve group management pages
  scripts/pi-hole/php/groups.php
Labels: Bugfix, Enhancement

#1252 Update devel from release v5.0
  api_db.php
  debug.php
  dns_records.php
  groups-adlists.php
  groups-clients.php
  groups.php
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-common.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/savesettings.php
  settings.php
  style/pi-hole.css
  style/vendor/bootstrap/css/bootstrap-multiselect.css
  style/vendor/bootstrap/css/bootstrap-select.min.css
  style/vendor/bootstrap/js/bootstrap-multiselect.js
  style/vendor/bootstrap/js/bootstrap-select.min.js
Labels: Release

#1276 Improvements for Teleporter
  scripts/pi-hole/php/customdns.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/teleporter.php
  settings.php
Labels: Bugfix, Discourse Feature Request, Enhancement

#1287 Fix autocomplete bug on group pages
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
Labels: Bugfix

#1294 Minor teleporter improvement
  settings.php
Labels: Bug in development, Bugfix

#1269 Add proper IP sorting to the groups->client table
  groups-clients.php
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/ip-address-sorting.js
Labels: Bugfix

#1266 Add new Pi-hole diagnostics system
  api_db.php
  messages.php
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/groups-common.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/php/header.php
  style/pi-hole.css
Labels: Enhancement

#1341 Remove glyphicons again.
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
Labels: Code maintenance

#1342 Update settings.js
  scripts/pi-hole/js/settings.js
Labels: Code maintenance

#1346 Enable a couple xo (ESLint) rules and rename utils
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  messages.php
  package.json
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/gravity.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/utils.js
Labels: Code maintenance

#1365 Regenerate package-lock.json
  package-lock.json
Labels: dependencies

#1373 footer.js: remove duplicate function.
  scripts/pi-hole/js/footer.js
Labels: Code maintenance

#1358 db_graph.js: move variable where it's used
  scripts/pi-hole/js/db_graph.js
Labels: Code maintenance

#1351 Remove redundant variable
  scripts/pi-hole/js/groups-clients.js
Labels: Code maintenance

#1367 Clean table classes
  db_queries.php
  dns_records.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  messages.php
  network.php
  queries.php
  settings.php
Labels: Code maintenance

#1368 Use `fa5` class on the sidebar toggle
  scripts/pi-hole/php/header.php
  style/pi-hole.css
Labels: Code maintenance

#1369 Minor HTML markup fixes.
  queryads.php
Labels: Code maintenance

#1372 Always use `!== -1` to check for a string's existence
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
Labels: Code maintenance

#1371 Replace custom httpGet() with $.ajax()
  scripts/pi-hole/js/debug.js
  scripts/pi-hole/js/queryads.js
Labels: Code maintenance

#1383 Update bootstrap-select and add missing .map files
  scripts/vendor/bootstrap-select.min.js
  scripts/vendor/bootstrap-select.min.js.map
  scripts/vendor/bootstrap-toggle.min.js.map
  style/vendor/bootstrap-select.min.css
Labels: Requires Testing, dependencies

#1384 Replace `$.each` with native methods.
  scripts/pi-hole/js/index.js
Labels: Code maintenance

#1385 Use `$` instead of `jQuery`.
  scripts/pi-hole/js/ip-address-sorting.js
Labels: Code maintenance, Requires Testing

#1400 Guard `gethostname()` calls
  scripts/pi-hole/php/header.php
Labels: Code maintenance

#1388 No console
  package.json
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/customdns.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/ip-address-sorting.js
Labels: Code maintenance

#1390 Remove duplicate token `div`
  auditlog.php
  db_graph.php
  db_lists.php
  db_queries.php
  network.php
  queries.php
Labels: Code maintenance

#1394 Remove version number from the Font Awesome folder.
  scripts/pi-hole/php/header.php
  style/vendor/font-awesome/css/all.min.css
  style/vendor/font-awesome/webfonts/fa-brands-400.eot
  style/vendor/font-awesome/webfonts/fa-brands-400.svg
  style/vendor/font-awesome/webfonts/fa-brands-400.ttf
  style/vendor/font-awesome/webfonts/fa-brands-400.woff
  style/vendor/font-awesome/webfonts/fa-brands-400.woff2
  style/vendor/font-awesome/webfonts/fa-regular-400.eot
  style/vendor/font-awesome/webfonts/fa-regular-400.svg
  style/vendor/font-awesome/webfonts/fa-regular-400.ttf
  style/vendor/font-awesome/webfonts/fa-regular-400.woff
  style/vendor/font-awesome/webfonts/fa-regular-400.woff2
  style/vendor/font-awesome/webfonts/fa-solid-900.eot
  style/vendor/font-awesome/webfonts/fa-solid-900.svg
  style/vendor/font-awesome/webfonts/fa-solid-900.ttf
  style/vendor/font-awesome/webfonts/fa-solid-900.woff
  style/vendor/font-awesome/webfonts/fa-solid-900.woff2
Labels: Code maintenance

#1376 Deduplicate js
  auditlog.php
  db_graph.php
  db_lists.php
  index.php
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/utils.js
Labels: Code maintenance

#1387 (Re-)Add API endpoints for list manipulations
  api.php
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/gravity.php
  scripts/pi-hole/php/groups.php
Labels: Bugfix, Enhancement

#1389 Move JS files where they are used.
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  network.php
  scripts/pi-hole/php/header.php
Labels: Code maintenance

#1366 CSS cleanup
  db_queries.php
  index.php
  style/pi-hole.css
Labels: Code maintenance

#1380 Update daterangepicker and add minified build
  db_graph.php
  db_lists.php
  db_queries.php
  scripts/pi-hole/php/header.php
  scripts/vendor/daterangepicker.js
  scripts/vendor/daterangepicker.min.js
  scripts/vendor/daterangepicker.min.js.map
  style/pi-hole.css
  style/vendor/daterangepicker.css
  style/vendor/daterangepicker.min.css
Labels: dependencies

#1402 Move animate.min.css style in the pages that use it
  scripts/pi-hole/php/header.php
Labels: Code maintenance

#1405 Fix sidebar docs link
  scripts/pi-hole/php/header.php
  style/pi-hole.css
Labels: Bugfix

#1406 Use `prop()` for the `disabled` attribute.
  scripts/pi-hole/js/debug.js
  scripts/pi-hole/js/gravity.js
  scripts/pi-hole/js/utils.js
Labels: Code maintenance

#1407 gravity.js: replace `removeAttr()` with `prop()`
  scripts/pi-hole/js/gravity.js
Labels: Code maintenance

#1408 Use `$(fn)`
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/customdns.js
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/queryads.js
  scripts/pi-hole/js/settings.js
Labels: Code maintenance
