Repository pi-hole/web, pull requests merged in 2020-06, with the labels that each got.

#1413 network.js: minor consistency changes
  scripts/pi-hole/js/network.js
Labels: Code maintenance

#1292 Allow spaces in groups when wrapping names in "..."
  groups-adlists.php
  groups.php
  scripts/pi-hole/php/groups.php
  style/pi-hole.css
Labels: Discussion, Enhancement

#1421 Show "zero" delays in the Query Log
  scripts/pi-hole/js/queries.js
Labels: Bugfix

#1419 Fix long-term blocking calculations
  api_db.php
  scripts/pi-hole/js/db_queries.js
Labels: Bugfix

#1424 Update chartjs to v2.9.3
  scripts/pi-hole/js/index.js
  scripts/vendor/Chart.min.js
Labels: Requires Testing, dependencies

#1429 Fix tailog pages IDs
  taillog-FTL.php
  taillog.php
Labels: Code maintenance

#1362 Update jQuery to v3.5.1.
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/queryads.js
  scripts/vendor/jquery.min.js
Labels: Requires Testing

#1356 Add support for HOSTNAME diagnostics message
  scripts/pi-hole/js/messages.js
Labels: Enhancement

#1431 Extend warning shown on server-side data processing errors
  scripts/pi-hole/js/db_queries.js
Labels: Enhancement

#1430 Update xo to v0.32.0 and regenerate package-lock.json
  package-lock.json
  package.json
Labels: dependencies

#1374 Enable radix ESLint rule
  package.json
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings.js
Labels: Code maintenance

#1420 Improve messages on the domain management pages
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/php/groups.php
Labels: Enhancement

#1442 Store NULL for empty descriptions and comments in the groups database tables
  scripts/pi-hole/php/groups.php
Labels: Enhancement

#1451 Remove the unused iCheck.min.js
  scripts/vendor/iCheck.min.js
Labels: Code maintenance

#1445 Tweak CSP
  scripts/pi-hole/php/header.php
Labels: Security

#1452 network.js: use `utils.datetime()`
  scripts/pi-hole/js/network.js
Labels: Code maintenance

#1453 footer.js: remove dead code.
  scripts/pi-hole/js/footer.js
Labels: Code maintenance

#1443 Prevent possible XSS attack vector in the input fields of the group section
  dns_records.php
  scripts/pi-hole/js/customdns.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/teleporter.php
  settings.php
Labels: Security

#1251 Fixes #1227 Fix possible warning when unlinking files
  api.php
Labels: Waiting on feedback

#1222 Improve filtering on table pages
  queries.php
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/utils.js
  style/themes/default-dark.css
  style/themes/default-light.css
Labels: Discourse Feature Request, Enhancement

#1475 Only show query types for which the count is larger than zero
  scripts/pi-hole/js/index.js
Labels: Bug in development, Bugfix
