Repository pi-hole/web, pull requests merged in 2020-12, with the labels that each got.

#1642 Improve documentation on Settings page
  settings.php
Labels: Enhancement

#1647 Pi-hole Web v5.2.1
  settings.php
Labels: PR: Approval Required, Release

#1640 Update devDependencies
  package-lock.json
  package.json
Labels: dependencies

#1664 Fix transactions in groups.php
  scripts/pi-hole/php/groups.php
Labels: Bugfix

#1676 Use new style constructors, fixes phpstan
  scripts/vendor/qrcode.php
Labels: Code maintenance
