Repository pi-hole/web, pull requests merged in 2020-04, with the labels that each got.

#1100 Disable text correction features, change types to make input fields easier to type in (especially for mobile devices)
  custom_dns.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  list.php
  queryads.php
  scripts/pi-hole/js/customdns.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings.js
  settings.php
Labels: Merge Conflicts

#1207 Update development from release/v5.0
  api_db.php
  auditlog.php
  custom_dns.php
  db_queries.php
  gravity.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  img/favicon.png
  img/favicons/android-chrome-192x192.png
  img/favicons/android-chrome-512x512.png
  img/favicons/apple-touch-icon.png
  img/favicons/favicon-16x16.png
  img/favicons/favicon-32x32.png
  img/favicons/favicon.ico
  img/favicons/manifest.json
  img/favicons/mstile-150x150.png
  img/favicons/safari-pinned-tab.svg
  list.php
  queries.php
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-common.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/ip-address-sorting.js
  scripts/pi-hole/js/list.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/php/add.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/get.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sub.php
  scripts/pi-hole/php/teleporter.php
  settings.php
  style/pi-hole.css
Labels: Code maintenance

#1214 Accept open-ended IPv6 addresses
  scripts/pi-hole/js/groups-common.js
Labels: Bugfix

#1206 Check for existence and readability of static leases file before trying to access it
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#1225 Fix IDN handling
  scripts/pi-hole/php/groups.php
Labels: Bugfix

#1121 Fix tooltip percentage computation and more...
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/index.js
Labels: Bugfix, Enhancement

#1210 Prevent multiple tabs from being opened when clicking on a regex link on the Query Log page
  scripts/pi-hole/js/queries.js
Labels: Bugfix

#1229 Custom DNS page -> Local DNS Records
  dns_records.php
  scripts/pi-hole/php/header.php
Labels: Enhancement

#1226 Allow ( and ) in adlist URLs.
  scripts/pi-hole/php/groups.php
Labels: Enhancement

#1230 Allow too long legend lines to break
  style/pi-hole.css
Labels: Bugfix
