Repository pi-hole/web, pull requests merged in 2020-07, with the labels that each got.

#1472 Tweak/custom dns
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#1208 Improve conditional forwarding settings
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: Enhancement

#1483 Update devDependencies and regenerate package-lock.json
  package-lock.json
  package.json
Labels: dependencies

#1517 Fix teleporter bug on hosts with . in their names
  scripts/pi-hole/php/teleporter.php
Labels: Bugfix

#1514 Fix ARPFLUSH button on the settings page
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#1519 Fix query types links on the dashboard (Query Types pie chart)
  scripts/pi-hole/js/index.js
Labels: Bugfix

#1518 Fix audit log button
  scripts/pi-hole/js/auditlog.js
  scripts/pi-hole/php/groups.php
Labels: Bugfix
