Repository pi-hole/web, pull requests merged in 2021-12, with the labels that each got.

#1995 Number of domains on adlist is total number not valid number
  scripts/pi-hole/js/groups-adlists.js
Labels: PR: Approval Required

#2006 Change default theme to auto light/dark theme
  scripts/pi-hole/php/theme.php
Labels: Discussion, PR: Approval Required

#2011 Improve interface settings
  scripts/pi-hole/php/savesettings.php
  settings.php
  style/pi-hole.css
Labels: Enhancement

#2003 Add padding to apple fav icon and set background to black
  img/favicons/apple-touch-icon.png
Labels: Discussion, PR: Approval Required

#2015 Reduce eye size
  style/pi-hole.css
Labels: PR: Approval Required

#2016 Pi-hole web v5.9
  .github/release.yml
  .github/workflows/phpstan.yml
  .github/workflows/test.yml
  README.md
  auditlog.php
  db_graph.php
  db_lists.php
  db_queries.php
  img/favicons/apple-touch-icon.png
  index.php
  messages.php
  network.php
  package-lock.json
  package.json
  queries.php
  queryads.php
  scripts/pi-hole/js/customcname.js
  scripts/pi-hole/js/customdns.js
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/db_lists.js
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/queryads.js
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/js/utils.js
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/theme.php
  settings.php
  style/pi-hole.css
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/lcars.css
  style/vendor/fonts/antonio/antonio-v1-latin-ext_latin-100.woff
  style/vendor/fonts/antonio/antonio-v1-latin-ext_latin-100.woff2
  style/vendor/fonts/antonio/antonio-v1-latin-ext_latin-700.woff
  style/vendor/fonts/antonio/antonio-v1-latin-ext_latin-700.woff2
  style/vendor/fonts/antonio/antonio-v1-latin-ext_latin-regular.woff
  style/vendor/fonts/antonio/antonio-v1-latin-ext_latin-regular.woff2
  style/vendor/fonts/antonio/antonio.css
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-700.woff
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-700.woff2
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-700italic.woff
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-700italic.woff2
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-italic.woff
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-italic.woff2
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-regular.woff
  style/vendor/fonts/ubuntu-mono/ubuntu-mono-v10-latin-ext_latin-regular.woff2
  style/vendor/fonts/ubuntu-mono/ubuntu-mono.css
Labels: Release

#2017 Add link to Pi-hole docs when showing dnsmasq warnings
  scripts/pi-hole/js/messages.js
Labels: Enhancement

#2029 Localize summary numbers
  api_FTL.php
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/index.js
Labels: Localization

#2031 Include FTL's DNS port in web status and give the temperature its own line
  scripts/pi-hole/js/index.js
  scripts/pi-hole/php/header.php
Labels: PR: Approval Required
