Repository pi-hole/web, pull requests merged in 2021-09, with the labels that each got.

#1875 Add httponly = true to persistent login cookie
  scripts/pi-hole/php/password.php
Labels: Security

#1871 Add BLOB reply type
  scripts/pi-hole/js/queries.js
Labels: Beta

#1845 Remove adlists tab from settings page
  settings.php
Labels: PR: Approval Required

#1886 Add delete button to message table
  messages.php
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/php/message.php
Labels: PR: Code Review Required
