Repository pi-hole/web, pull requests merged in 2021-11, with the labels that each got.

#1975 Revert "Remove duplicated code as it is already part of utils.stateLoadCallback"
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/messages.js
Labels: Bugfix, PR: Approval Required

#1943 Remove traces of leftover API_PRIVACY_MODE
  queries.php
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: PR: Approval Required

#1977 Use theme gridColor and ticksColor in long time graph
  db_graph.php
  scripts/pi-hole/js/db_graph.js
  scripts/pi-hole/js/index.js
Labels: PR: Approval Required

#1966 Redo of Fixes background of the dark-midnight theme #1961
  style/themes/default-darker.css
Labels: PR: Approval Required

#1970 Fix PHP 8 incompatibility on settings page
  scripts/pi-hole/php/savesettings.php
Labels: Bugfix

#1982 Fix DHCP tables button column
  scripts/pi-hole/js/settings.js
Labels: PR: Approval Required

#1979 Remove obsolete code from network.php
  network.php
Labels: PR: Approval Required

#1990 Add bounce animation to Pi-hole diagnosis warning triangle
  scripts/pi-hole/php/header.php
  style/pi-hole.css
Labels: Enhancement
