Repository pi-hole/web, pull requests merged in 2021-02, with the labels that each got.

#1737 Pi-hole web v5.4
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/password.php
Labels: Release, Security

#1743 Don't count new status types as blocked queries in long-term data
  api_db.php
  scripts/pi-hole/js/db_queries.js
Labels: PR: Approval Required

#1749 Add update command & documentation link
  scripts/pi-hole/php/footer.php
Labels: UI enhancement

#1731 Add Pi-hole darker theme
  scripts/pi-hole/php/theme.php
  style/themes/default-dark.css
  style/themes/default-darker.css
Labels: Bugfix, Enhancement
