Repository pi-hole/web, pull requests merged in 2022-01, with the labels that each got.

#2054 Rework the temp info in the status panel
  scripts/pi-hole/php/header.php
Labels: PR: Code Review Required

#2062 Use piholeStatus() in header.php
  scripts/pi-hole/php/header.php
Labels: PR: Approval Required

#2070 [Maintenance] Sync Master back to Dev when code is pushed to master
  .github/release.yml
  .github/workflows/sync-back-to-dev.yml
Labels: internal

#2072 Add stale workflow
  .github/workflows/stale.yml
Labels: internal

#2077 Change pinned to internal exemption of stale issues
  .github/workflows/stale.yml
Labels: internal

#2083 Revert "sync: master to devel"
  .github/workflows/stale.yml
Labels: internal

#2085 [Config] Add dco.yml to .github folder
  .github/dco.yml
Labels: internal
