Repository pi-hole/web, pull requests merged in 2022-02, with the labels that each got.

#2112 Add navigation above all datatables
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/settings.js
Labels: Discourse Feature Request

#2021 Decrease resource usage of CSS animations
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/php/footer.php
  settings.php
  style/pi-hole.css
  style/themes/lcars.css
Labels: Discussion

#2120 Manual sync master to devel. It went wrong before
  .github/workflows/stale.yml
Labels: internal

#2084 Pi-hole web v5.11
  .user.php.ini
  api.php
  api_FTL.php
  api_db.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  index.php
  package-lock.json
  package.json
  queries.php
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings.js
  scripts/pi-hole/js/utils.js
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/customcname.php
  scripts/pi-hole/php/customdns.php
  scripts/pi-hole/php/footer.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/gravity.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/queryads.php
  scripts/pi-hole/php/teleporter.php
  settings.php
  style/pi-hole.css
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/lcars.css
Labels: Release, internal
