Repository pi-hole/web, pull requests merged in 2022-08, with the labels that each got.

#2280 Fix/php indentation and enable editorconfig-checker
  .codespellignore
  .editorconfig
  .github/dco.yml
  .github/workflows/editorconfig-checker
  .github/workflows/editorconfig-checker.yml
  LICENSE
  README.md
  api.php
  api_FTL.php
  api_db.php
  auditlog.php
  cname_records.php
  db_graph.php
  db_lists.php
  db_queries.php
  debug.php
  dns_records.php
  gravity.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  index.php
  messages.php
  network.php
  queries.php
  queryads.php
  scripts/pi-hole/php/FTL.php
  scripts/pi-hole/php/api_token.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/customcname.php
  scripts/pi-hole/php/customdns.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/footer.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/gravity.php
  scripts/pi-hole/php/gravity.sh.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/loginpage.php
  scripts/pi-hole/php/message.php
  scripts/pi-hole/php/network.php
  scripts/pi-hole/php/password.php
  scripts/pi-hole/php/queryads.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sidebar.php
  scripts/pi-hole/php/tailLog.php
  scripts/pi-hole/php/teleporter.php
  scripts/pi-hole/php/theme.php
  scripts/pi-hole/php/update_checker.php
  settings.php
  style/pi-hole.css
  style/themes/default-darker.css
  taillog-FTL.php
  taillog.php
Labels: internal

#2272 Explicit set minor and patch version on used actions
  .github/workflows/codeql.yml
  .github/workflows/codespell.yml
  .github/workflows/phpstan.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
Labels: PR: Approval Required, internal

#2288 Enforce Symfony PHP code style
  .github/workflows/php-cs-fixer.yml
  .gitignore
  .php-cs-fixer.dist.php
  api.php
  api_FTL.php
  api_db.php
  auditlog.php
  cname_records.php
  db_graph.php
  db_lists.php
  db_queries.php
  debug.php
  dns_records.php
  gravity.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  index.php
  messages.php
  network.php
  queries.php
  queryads.php
  scripts/pi-hole/php/FTL.php
  scripts/pi-hole/php/api_token.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/customcname.php
  scripts/pi-hole/php/customdns.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/debug.php
  scripts/pi-hole/php/footer.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/gravity.php
  scripts/pi-hole/php/gravity.sh.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/loginpage.php
  scripts/pi-hole/php/message.php
  scripts/pi-hole/php/network.php
  scripts/pi-hole/php/password.php
  scripts/pi-hole/php/queryads.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sidebar.php
  scripts/pi-hole/php/tailLog.php
  scripts/pi-hole/php/teleporter.php
  scripts/pi-hole/php/theme.php
  scripts/pi-hole/php/update_checker.php
  settings.php
  taillog-FTL.php
  taillog.php
Labels: Code maintenance, PR: Approved

#2293 To Yoda or Not to Yoda
  .php-cs-fixer.dist.php
  api_FTL.php
  api_db.php
  queries.php
  scripts/pi-hole/php/FTL.php
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/gravity.php
  scripts/pi-hole/php/gravity.sh.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/message.php
  scripts/pi-hole/php/network.php
  scripts/pi-hole/php/password.php
  scripts/pi-hole/php/savesettings.php
  scripts/pi-hole/php/sidebar.php
  scripts/pi-hole/php/teleporter.php
  scripts/pi-hole/php/theme.php
  scripts/pi-hole/php/update_checker.php
  settings.php
Labels: Code maintenance, internal

#2300 Extend list of files to be ignored by codespell
  .github/workflows/codespell.yml
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/php/teleporter.php
Labels: PR: Approval Required, internal

#2298 Improve top right menu and sidebar
  index.php
  scripts/pi-hole/js/footer.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/header_authenticated.php
  scripts/pi-hole/php/sidebar.php
  style/pi-hole.css
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/lcars.css
Labels: PR: Approved

#2303 Change docker upgrade link in footer
  scripts/pi-hole/php/footer.php
Labels: PR: Approved

#2287 Remove Content-Security-Policy meta tag
  scripts/pi-hole/php/header.php
Labels: Security, PR: Approved

#2301 Remove email functionality
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/savesettings.php
  settings.php
Labels: PR: Approved

#2308 Restore save functionality
  settings.php
Labels: PR: Approval Required

#2314 Revert empty domain dot replacement
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/groups.php
Labels: PR: Approval Required
