Repository pi-hole/web, pull requests merged in 2022-12, with the labels that each got.

#2450 Update PHPStan
  .github/workflows/phpstan.yml
  composer.json
  phpstan.neon.dist
Labels: PR: Approval Required

#2454 Remove ignore section from dependabot
  .github/dependabot.yml
Labels: PR: Approval Required, internal

#2457 Use github cli to sync master back to devel
  .github/workflows/sync-back-to-dev.yml
Labels: PR: Approval Required, internal

#2456 Add merge conflict workflow
  .github/workflows/merge-conflict.yml
Labels: PR: Approval Required

#2464 Fix phpstan action
  composer.lock
Labels: internal

#2463 Pi-hole web v5.18
  .github/dependabot.yml
  .github/workflows/codeql.yml
  .github/workflows/codespell.yml
  .github/workflows/editorconfig-checker.yml
  .github/workflows/merge-conflict.yml
  .github/workflows/php-cs-fixer.yml
  .github/workflows/phpstan.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
  api_FTL.php
  composer.json
  composer.lock
  package-lock.json
  package.json
  phpstan.neon.dist
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/utils.js
  scripts/pi-hole/php/queryads.php
  style/pi-hole.css
Labels: internal

#2469 Shorten no merge conflict message
  .github/workflows/merge-conflict.yml
Labels: PR: Approval Required

#2419 Provide fake username on login form
  login.php
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/lcars.css
Labels: PR: Approval Required
