Repository pi-hole/web, pull requests merged in 2022-06, with the labels that each got.

#2219 Do not use IPvX from setupVars in $AUTHORIZED_HOSTNAMES
  scripts/pi-hole/php/auth.php
Labels: PR: Approved

#2224 Update dependabot.yml to add reviewers
  .github/dependabot.yml
Labels: internal

#2212 Also check wildcard domains for validity before adding
  scripts/pi-hole/php/groups.php
Labels: PR: Approval Required

#2225 Show warning triangle only if logged in
  api_db.php
Labels: Discussion

#2227 Upgrade stale action to v5
  .github/workflows/stale.yml
Labels: internal

#2228 Add stale-issue-reason
  .github/workflows/stale.yml
Labels: internal

#2229 Add github-action to dependabot
  .github/dependabot.yml
Labels: internal

#2231 Add .editorconfig
  .editorconfig
Labels: Code maintenance, PR: Approval Required, internal

#2232 Adjust debug log scroll position
  scripts/pi-hole/js/debug.js
Labels: UI enhancement

#2233 Editorconfig checker
  .editorconfig
  .github/workflows/editorconfig-checker
Labels: PR: Approval Required, internal

#2238 Add stickler-CI to test yaml and mkdown files
  .stickler.yml
Labels: PR: Approval Required, internal
