Repository pi-hole/web, pull requests merged in 2022-09, with the labels that each got.

#2319 Remove unnecssary <br> from adlist details
  scripts/pi-hole/js/groups-adlists.js
Labels: PR: Approval Required

#2324 Include link to current docker tag if on docker. Closes #2323
  scripts/pi-hole/php/footer.php
  scripts/pi-hole/php/update_checker.php
Labels: Bugfix

#2332 v5.14.2
  package-lock.json
  package.json
  scripts/pi-hole/php/password.php
  scripts/pi-hole/php/update_checker.php
Labels: internal

#2336 Do not apply IDNA conversion to RegEx domains
  scripts/pi-hole/php/groups.php
Labels: PR: Approval Required

#2285 Set Samesite=Strict for PHP session cookie
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/password.php
Labels: Security, PR: Approval Required

#2344 Update browserlist
  package-lock.json
  package.json
Labels: PR: Approval Required

#2320 Add interpretation for Pi-hole message type ADLIST
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/messages.js
Labels: PR: Approval Required

#2349 v5.15
  api.php
  groups-domains.php
  package-lock.json
  package.json
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/php/auth.php
  scripts/pi-hole/php/database.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/header_authenticated.php
  scripts/pi-hole/php/password.php
  scripts/pi-hole/php/teleporter.php
  style/pi-hole.css
  style/themes/lcars.css
Labels: internal

#2338 Reverse logic of in/exlcuding queries from long-term database and rename queryType => statusType
  api_db.php
  scripts/pi-hole/js/db_queries.js
Labels: PR: Approval Required

#2356 Read DOCKER_VERSION from version file instead of env variable
  scripts/pi-hole/php/update_checker.php
Labels: PR: Approval Required

#2363 v5.15.1
  .github/workflows/stale.yml
  README.md
  api_db.php
  package-lock.json
  package.json
  scripts/pi-hole/js/db_queries.js
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/update_checker.php
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/lcars.css
Labels: internal

#2366 Allow the root zone `.` to be excluded from top lists
  scripts/pi-hole/php/func.php
Labels: PR: Approval Required

#2370 Remove additional space in Cookie header
  scripts/pi-hole/php/func.php
Labels: PR: Approval Required
