Repository pi-hole/web, pull requests merged in 2022-11, with the labels that each got.

#2425 Remove obsolete loginpage
  scripts/pi-hole/php/loginpage.php
Labels: PR: Approval Required

#2420 Disable spellcheckers from inspecting the password
  login.php
Labels: PR: Approved

#2434 Fix doughnutTooltip if total percentage of shown slices is less than 0.1%
  scripts/pi-hole/js/index.js
Labels: PR: Approved

#2411 Require auth for more API endpoints
  api_FTL.php
Labels: Discussion, PR: Approved

#2436 Use xo 0.53.0 and fix errors
  package-lock.json
  package.json
  scripts/pi-hole/js/utils.js
Labels: Discussion, PR: Approval Required
