Repository pi-hole/web, pull requests merged in 2023-07, with the labels that each got.

#2613 Fix donate button
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/settings-dns-records.js
  scripts/pi-hole/lua/sidebar.lp
  scripts/pi-hole/lua/theme.lua
  settings-api.lp
  settings-dhcp.lp
  settings-dns.lp
  settings-dnsrecords.lp
  settings-privacy.lp
  style/pi-hole.css
Labels: v6

#2616 Change the load order of some CSS files to fix a few visual issues
  scripts/pi-hole/lua/header.lp
  scripts/pi-hole/lua/header_authenticated.lp
Labels: v6

#2624 Dependabot for v6 branch
  .github/dependabot.yml
  scripts/pi-hole/php/func.php
Labels: internal

#2639 Fix running gravity from the web UI
  scripts/pi-hole/js/gravity.js
Labels: Bugfix, Bug in development

#2601 Do not try to remove stale label on PRs
  .github/workflows/stale.yml
Labels: internal

#2640 Fix check of ticked non-custom DNS servers
  scripts/pi-hole/js/settings-dns.js
Labels: Bugfix

#2658 Tweak advenced filtering box (Query log page)
  queries.lp
  scripts/pi-hole/js/queries.js
Labels: v6

#2663 Tweak Query Log
  queries.lp
  scripts/pi-hole/js/queries.js
  scripts/pi-hole/js/utils.js
Labels: v6

#2668 Revert "Fix login page rediction"
  scripts/pi-hole/js/login.js
Labels: Bugfix, v6
