Repository pi-hole/web, pull requests merged in 2023-01, with the labels that each got.

#2473 Add action to close stale PR
  .github/workflows/stale_pr.yml
Labels: internal

#2493 v5.18.1
  .github/workflows/codeql.yml
  .github/workflows/codespell.yml
  .github/workflows/editorconfig-checker.yml
  .github/workflows/merge-conflict.yml
  .github/workflows/php-cs-fixer.yml
  .github/workflows/phpstan.yml
  .github/workflows/stale.yml
  .github/workflows/sync-back-to-dev.yml
  .github/workflows/test.yml
  auditlog.php
  cname_records.php
  composer.lock
  db_graph.php
  db_lists.php
  db_queries.php
  debug.php
  dns_records.php
  gravity.php
  groups-adlists.php
  groups-clients.php
  groups-domains.php
  groups.php
  index.php
  login.php
  messages.php
  network.php
  package-lock.json
  package.json
  queries.php
  queryads.php
  scripts/pi-hole/js/queryads.js
  scripts/pi-hole/php/footer.php
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/header.php
  scripts/pi-hole/php/queryads.php
  settings.php
  style/pi-hole.css
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/lcars.css
  taillog-FTL.php
  taillog.php
Labels: Release, internal

#2497 Add default value for $ver in func.php
  scripts/pi-hole/php/func.php
Labels: PR: Approval Required

#2502 Show two decimals on doughnutTooltip if total share shown is less than 1%
  scripts/pi-hole/js/index.js
Labels: PR: Approval Required

#2498 Tweak deleting message
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/network.js
Labels: PR: Approval Required

#2507 Attenuate non-domain warning
  scripts/pi-hole/js/groups-adlists.js
Labels: PR: Approval Required

#2479 Do not return 'false' if IDNA<->UNICODE conversion fails
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/groups.php
Labels: PR: Code Review Required

#2509 Pi-hole web v5.18.2
  composer.lock
  scripts/pi-hole/js/groups-adlists.js
  scripts/pi-hole/js/groups-clients.js
  scripts/pi-hole/js/groups-domains.js
  scripts/pi-hole/js/groups.js
  scripts/pi-hole/js/index.js
  scripts/pi-hole/js/messages.js
  scripts/pi-hole/js/network.js
  scripts/pi-hole/php/func.php
  scripts/pi-hole/php/groups.php
  scripts/pi-hole/php/password.php
Labels: internal

#2512 Hotfix v5.18.3
  logout.php
  scripts/pi-hole/php/password.php
  scripts/pi-hole/php/persistentlogin_token.php
Labels: internal
