Repository pi-hole/web, pull requests merged in 2025-03, with the labels that each got.

#3283 Fix top lists links on the dashboard
  scripts/js/index.js
Labels: Bugfix

#3286 Sort IPv4 before IPv6 addresses on the network overview
  scripts/js/network.js
Labels: Discourse Feature Request

#3284 Sort interfaces
  scripts/js/interfaces.js
  style/pi-hole.css
Labels: UI enhancement

#3329 Remove a few unused CSS rules from pi-hole.css and LCARS theme
  style/pi-hole.css
  style/themes/lcars.css
Labels: Code maintenance
