Repository pi-hole/web, pull requests merged in 2025-01, with the labels that each got.

#3187 Add possibility to assign groups to newly added entries from the beginning
  groups-clients.lp
  groups-domains.lp
  groups-lists.lp
  scripts/js/groups-clients.js
  scripts/js/groups-common.js
  scripts/js/groups-domains.js
  scripts/js/groups-lists.js
  scripts/js/groups.js
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/high-contrast-dark.css
  style/themes/high-contrast.css
  style/themes/lcars.css
Labels: Discourse Feature Request, Pi-hole v6.0

#3185 Show DNSSEC status icon (if applicable)
  scripts/js/queries.js
Labels: Pi-hole v6.0

#3197 Use new dnssec.color instead of the removed dnssecClass variable
  scripts/js/queries.js
Labels: Bugfix, Pi-hole v6.0

#3198 Tweak bar colors used by "Total queries" graphic
  style/pi-hole.css
  style/themes/default-dark.css
  style/themes/default-darker.css
  style/themes/default-light.css
  style/themes/high-contrast-dark.css
  style/themes/high-contrast.css
  style/themes/lcars.css
Labels: Pi-hole v6.0

#3203 Modify status text if a reply was received for clarify
  scripts/js/queries.js
Labels: UI enhancement, Pi-hole v6.0
